const {chromium} = require('playwright');
const path = require('node:path');
const assert = require('node:assert/strict');
const {pathToFileURL} = require('node:url');

(async () => {
  const browser = await chromium.launch({headless:true,executablePath:process.env.SCANNER_BROWSER || undefined});
  const page = await browser.newPage({viewport:{width:1280,height:1100},colorScheme:'light'});
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const target = process.argv[2] || pathToFileURL(path.resolve('output/ip-scanner-demo.html')).href;
  await page.goto(target);
  await page.locator('[data-ui="occupied"]').filter({hasText:'18'}).waitFor();
  assert.equal(await page.locator('[data-ui="unobserved"]').innerText(),'233');
  assert.equal(await page.locator('[data-ui="known"]').innerText(),'3');
  assert.equal(await page.locator('[data-ui="map"] button').count(),254);
  await page.screenshot({path:'output/ip-scanner-desktop.png',fullPage:true});
  await page.locator('[data-tab="free"]').click();
  assert.match(await page.locator('[data-ui="result-count"]').innerText(),/233/);
  await page.locator('[data-ui="search"]').fill('192.168.1.2');
  assert.match(await page.locator('[data-ui="table-body"]').innerText(),/192\.168\.1\.2/);
  await page.locator('[data-ui="search"]').fill('');
  await page.locator('[data-tab="ranges"]').click();
  assert.match(await page.locator('[data-ui="table-head"]').innerText(),/עד כתובת/);
  await page.locator('[data-ip="192.168.1.10"]').click();
  assert.match(await page.locator('[data-ui="table-body"]').innerText(),/Home Assistant/);
  await page.locator('[data-edit="192.168.1.10"]').click();
  await page.locator('[data-ui="alias-input"]').fill('<img src=x onerror=alert(1)>');
  await page.locator('[data-action="save-alias"]').click();
  await page.locator('[data-ui="alias-dialog"]').waitFor({state:'hidden'});
  assert.match(await page.locator('[data-ui="table-body"]').innerText(),/<img src=x/);
  assert.equal(await page.locator('[data-ui="table-body"] img').count(),0);
  await page.locator('[data-edit="192.168.1.10"]').click();
  await page.locator('[data-ui="alias-input"]').fill('Home Assistant');
  await page.locator('[data-action="save-alias"]').click();
  await page.locator('[data-ui="alias-dialog"]').waitFor({state:'hidden'});
  await page.locator('[data-ui="search"]').fill('');
  await page.locator('[data-action="scan"]').click();
  await page.locator('[data-ui="scan-label"]').filter({hasText:'עצור'}).waitFor();
  await page.locator('[data-action="scan"]').click();
  await page.locator('[data-ui="scan-label"]').filter({hasText:'סרוק'}).waitFor();
  await page.locator('[data-action="scan"]').click();
  await page.locator('[data-ui="scan-label"]').filter({hasText:'סרוק'}).waitFor({timeout:7000});
  await page.locator('[data-action="theme"]').click();
  await page.screenshot({path:'output/ip-scanner-dark.png',fullPage:true});
  for (const width of [1024,736,390,320]) {
    await page.setViewportSize({width,height:1000});
    const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth);
    assert.equal(overflow,false,`Unexpected page overflow at ${width}px`);
    if (width === 390) await page.screenshot({path:'output/ip-scanner-mobile.png',fullPage:true});
  }
  const downloadPromise = page.waitForEvent('download');
  await page.locator('[data-action="export"]').click();
  const download = await downloadPromise;
  assert.match(download.suggestedFilename(),/ip-scanner.*\.csv/);
  assert.deepEqual(errors,[]);
  console.log('UI passed: counts, tables, ranges, map, names, escaping, scan/cancel, CSV, themes, 320–1280px.');
  await browser.close();
})().catch(error => {console.error(error);process.exit(1);});
